config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :annoyers
  resources :nodes
  resources :reminders do
    resources :recents
  end

  # graphql
  post '/graphql', to: 'graphql#query'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine,
    at: "/graphiql",
    graphql_path: "/graphql"
  end
  # end graphql
end

app/models/annoyer.rb
class Annoyer < ActiveRecord::Base
  has_many :nodes, dependent: :destroy
  has_many :reminders, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :color, presence: true, length: { minimum: 6 }
  validates :user_id, presence: true

  def latest_reminder
    recents = Recent.where(reminder_id: reminders.select(:id))
    recent = recents.order('created_at ASC').last
    if recent
      Reminder.where(id: recent.reminder_id).first
    end
  end

  def self.all_recents(user_id)
    annoyers = Annoyer.where(user_id: user_id)
    reminder_ids = Reminder.select(:id).where(annoyer_id: annoyers.map(&:id))
    all_recents = Recent.where(reminder_id: reminder_ids)
    all_recents.order("created_at desc").limit("10")
  end
end

app/controllers/annoyers_controller.rb
class AnnoyersController < ApplicationController
  before_action :validate_user, only: [:show, :edit, :update, :destroy]
  before_action :valid_session, only: [:new, :index, :create]

  def index
    @presenter = AnnoyersOverview.new(current_user.id)
  end

  def new
    @annoyer = Annoyer.new
  end

  def create
    @annoyer = Annoyer.new(annoyer_params)
    if @annoyer.save
      redirect_to(@annoyer)
    else
      render('new')
    end
  end

  def show
    @annoyer = Annoyer.find(params[:id])
    @node = Node.new
    @reminder = Reminder.new
  end

  def edit
    @annoyer = Annoyer.find(params[:id])
  end

  def update
    @annoyer = Annoyer.find(params[:id])
    if @annoyer.update(annoyer_params)
      redirect_to(@annoyer)
    else
      redirect_to(edit_annoyer_path(@annoyer))
    end
  end

  def destroy
    annoyer = Annoyer.find(params[:id])
    annoyer.destroy
    redirect_to(annoyers_path)
  end

  private
    def annoyer_params
      param = params.require(:annoyer).permit(:title, :color)
      param.merge!(user_id: current_user.id)
    end

    def validate_user
      annoyer = Annoyer.find(params[:id])
      if current_user
        if current_user.id != annoyer.user_id
          redirect_to(root_path)
        end
      else
        redirect_to(root_path)
      end
    end

    def valid_session
      if !current_user
        redirect_to(root_path)
      end
    end
end

app/helpers/annoyers_helper.rb
module AnnoyersHelper
end

app/views/annoyers/_form.html.haml
= form_for @annoyer do |f|
  = render 'shared/error', object: @annoyer
  %hr
  %p just enter an Annoyer name, to annoy you:
  %p
    .input-group.input-group-lg
      %span.input-group-addon
        %span.glyphicon.glyphicon-font
      = f.text_field :title, :class => 'form-control'
  %hr
  %p and pick a color of your choice:
  .row
    .col-md-2
      = f.radio_button :color, '0433ff'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#0433ff;font-size:20px;' }
    .col-md-2
      = f.radio_button :color, 'aa7942'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#aa7942;font-size:20px;' }
    .col-md-2
      = f.radio_button :color, '53d8d9'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#00fdff;font-size:20px;' }
    .col-md-2
      = f.radio_button :color, '3dd452'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#00f900;font-size:20px;' }
    .col-md-2
      = f.radio_button :color, 'ff40ff'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#ff40ff;font-size:20px;' }
    .col-md-2
      = f.radio_button :color, 'ff9300'
      %span.glyphicon.glyphicon-tint{ :style => 'color:#ff9300;font-size:20px;' }
  %hr
  .row
    .col-md-12
      = f.hidden_field :user_id, :value => current_user.id
      = f.submit 'Annoy me!', :class => 'btn btn-primary btn-lg pull-right'

app/views/annoyers/edit.html.haml
%h1 Edit "#{@annoyer.title}"
= render :partial => 'form'

app/views/annoyers/index.html.haml
%h2 Annoyer Overview and Dashboard
%hr
.row
  .col-md-6
    %h3 Your Annoyers:
    - @presenter.annoyers.each do |annoyer_data|
      .annoyers-overview{ :style => "border-left-color:##{annoyer_data[:annoyer].color};" }
        %h4.list-group-item-heading= annoyer_data.annoyer.title
        .label-annoyer
          = "Nodes (#{annoyer_data.node_count})"
        .label-annoyer
          - if annoyer_data[:date]
            = "latest recent: #{annoyer_data.date} (#{annoyer_data.reminder})"
          - else
            = "You never did that..."
        .clearfix
          = link_to "Manage", annoyer_path(annoyer_data.annoyer), :class => "btn btn-primary btn-sm pull-right"
  .col-md-6
    %h3 Your 10 latest Recents:
    %ul
      - @presenter.recents.each do |recent|
        %li.list-group-item.list-group-item-recent{ :style => "background-color:##{recent.color}" }
          %strong= "#{recent.reminder} on "
          %i= recent.date

app/views/annoyers/new.html.haml
%h1 Add a new Annoyer
= render :partial => 'form'

app/views/annoyers/show.html.haml
%h1= @annoyer.title
%hr
.row
  .col-md-8.col-md-offset-2
    #nodes_container
%hr
.row
  .col-md-8.col-md-offset-2
    #reminders_container
%hr
= link_to annoyer_path(@annoyer), method: :delete, data: { confirm: 'Are you sure?' } do
  %span.btn.btn-danger.btn-sm.pull-right{ :style => "margin-bottom:20px;" }
    Delete this annoyer
    %span.pull-right.glyphicon.glyphicon-trash{ :style => "font-size:16px;margin-left:5px;" }
= link_to edit_annoyer_path(@annoyer) do
  .clearfix
    %span.btn.btn-primary.btn-sm.pull-right{ :style => "margin-bottom:20px;" }
      Edit this annoyer
      %span.pull-right.glyphicon.glyphicon-cog{ :style => "font-size:16px;margin-left:5px;" }
= javascript_include_tag 'react_compiled', 'data-turbolinks-track' => true