config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :annoyers
  resources :nodes
  resources :reminders do
    resources :recents
  end

  # graphql
  post '/graphql', to: 'graphql#query'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine,
    at: "/graphiql",
    graphql_path: "/graphql"
  end
  # end graphql
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  enum repeat_values: ["Day", "Week", "Month", "Year"]

  belongs_to :annoyer
  has_many :recents, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :frequency, presence: true, length: { minimum: 1 }, :numericality => { :greater_than => 0}
  validates :repeat, presence: true, inclusion: { in: repeat_values.keys}
  validates :annoyer_id, presence: true

  def latest_recent
    recents.last
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def create
    validate_user(params.require(:reminder)['annoyer_id']) do |annoyer|
      @annoyer = annoyer
      @reminder = Reminder.new(reminder_params)

      if @reminder.save
        redirect_to(@annoyer)
      else
        render('annoyers/show')
      end
    end
  end

  def destroy
    reminder = Reminder.find(params[:id])
    validate_user(Annoyer.find(reminder.annoyer_id)) do |annoyer|
      reminder.destroy
      redirect_to(annoyer_path(annoyer))
    end
  end

  private
    def reminder_params
      params.require(:reminder).permit(:title, :frequency, :repeat, :annoyer_id)
    end

    def validate_user(annoyer_id)
      annoyer = Annoyer.find(annoyer_id)
      if current_user
        if current_user.id == annoyer.user_id
          yield annoyer
        else
          redirect_to(root_path)
        end
      else
        redirect_to(root_path)
      end
    end
end

app/helpers/reminders_helper.rb
module RemindersHelper
  def format_frequency(number)
    if number > 2
      "#{number} times"
    else
      if number == 1
        "once"
      else
        "twice"
      end
    end
  end

  def get_latest_date(reminder)
    latest_recent = reminder.recents.order("created_at").last
    latest_recent.created_at.to_formatted_s(:long_ordinal)
  end

  def frequency_rate_formatted(reminder)
    case reminder.repeat
    when "Day"
      cycle = Time.now - 24.hours
    when "Week"
      cycle = Time.now - 7.days
    when "Month"
      cycle = Time.now - 1.month
    when "Year"
      cycle = Time.now - 1.year
    end

    amount = reminder.recents.where("created_at > ?", cycle).count

    case amount
    when 0
      "never"
    when 1
      "once"
    when 2
      "twice"
    else
      "#{amount} times"
    end
  end
end

app/views/reminders/_form.html.haml
%p
  Add a new Reminder!
  - reminder = @reminder || Reminder.new
  = form_for reminder do |f|
    = render 'shared/error', object: reminder
    %p
      .row
        .col-md-12
          .input-group
            %span.input-group-addon
              %span.glyphicon.glyphicon-font
            = f.text_field :title, :class => 'form-control', :placeholder => 'title'
    %p
      .row
        .col-md-6
          %span how often:
          .input-group
            %span.input-group-addon
              %span.glyphicon.glyphicon-scale
            = f.number_field :frequency, :class => 'form-control', :min => '1', :value => '1'
        .col-md-6
          %span ...times each:
          .form-group
            = f.select :repeat, ['Day', 'Week', 'Month', 'Year'], {}, :class => 'form-control'
    %p
      = f.hidden_field :annoyer_id, :value => @annoyer.id
      = f.submit 'create reminder!', :class => 'btn btn-primary btn pull-right'

app/views/reminders/_reminder.html.haml
.list-group-item
  %h4= reminder.title
  %div{ :style => "margin:5px;" }
    .label.label-annoyer-opacity{ :style => "background-color:##{@annoyer.color};" }
      %i
        %strong= format_frequency(reminder.frequency)
        a
        %strong= reminder.repeat
  %div{ :style => "margin:5px;" }
    You did it
    .label.label-annoyer-opacity{ :style => "background-color:##{@annoyer.color};" }
      %i
        = frequency_rate_formatted(reminder)
    = "this #{reminder.repeat}"
    = link_to '... and I did it right now!', new_reminder_recent_path(:reminder_id => reminder)
  %div{ :style => "margin:5px;" }
    - if reminder.recents.any?
      You did that the last time on
      %span.label.label-annoyer-opacity{ :style => "background-color:##{@annoyer.color};" }
        = get_latest_date(reminder)
    - else
      = "You never did that at all!"
  = link_to reminder, method: :delete do
    .clearfix
      %span.pull-right.glyphicon.glyphicon-trash{ :style => "font-size:16px;" }